---
- homebrew:
    name: [
      vim, zsh, tree, tig, coreutils,
      go, node, jq,
      moreutils, fzf, cmake, rg, automake, bison,
      watch, telnet
    ]
    state: present
  when: skip_slow_stuff != 'yes'
- homebrew_cask:
    name: [
      docker, karabiner-elements,
      multifirefox, iterm2, obs, postico,
      mudlet,
      vlc, cleanmymac, kindle, spotify,
      caffeine, unity, omnifocus, evernote,
      sketch, visual-studio-code,
      zoomus, skype, oracle-jdk, steam, discord, skype,
      1password, 1password-cli, intellij-idea,
      slack, postman, postgres, vagrant
    ]
    state: present
  when: skip_slow_stuff != 'yes'
