---
- homebrew:
    name: [
      vim, zsh, tree, tig, coreutils,
      go, node, jq,
      moreutils, fzf, cmake, rg, automake, bison,
      watch, telnet,
      redis
    ]
    state: present
  when: skip_slow_stuff != 'yes' and machine_type == 'workstation'
- homebrew_cask:
    name: [
      docker, karabiner-elements,
      multifirefox, iterm2, obs, postico,
      mudlet,
      vlc, cleanmymac, kindle, spotify,
      caffeine, unity, omnifocus, evernote,
      sketch, visual-studio-code,
      zoomus, skype, oracle-jdk, steam, discord, skype,
      1password, 1password-cli, intellij-idea,
      slack, postman, postgres, vagrant
    ]
    state: present
  when: skip_slow_stuff != 'yes' and machine_type == 'workstation'

- yum_repository:
    name: carlwgeorge-ripgrep-epel-7.repo
    description: why is description required
    baseurl: https://copr-be.cloud.fedoraproject.org/results/carlwgeorge/ripgrep/epel-7-$basearch/
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/carlwgeorge/ripgrep/pubkey.gpg
  become_user: root
  when: machine_type == 'vps'

- yum:
    name: [ripgrep, cmake, epel-release, python2-certbot-nginx, nginx]
    state: present
  become: yes
  when: skip_slow_stuff != 'yes' and machine_type == 'vps'
