# terminals
# urxvt&
# urxvt&
# urxvt&
# urxvt&
urxvtd -q -o -f

#screesaver stuff
xscreensaver -no-splash &


# keyboard stuff
xset r rate 250 30 &
setxkbmap -option terminate:ctrl_alt_bksp &

# natural scrolling
xinput set-button-map 12 1 2 3 5 4 7 6 8 9 10 11 12

# xmodmap
# holy crap this is dumb
( sleep 1; xmodmap $HOME/.Xmodmap )&

exec xmonad
