# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sepia
version:      0.97
version_from: lib/Sepia.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
