---
- name: gitconfig
  file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: ~/.gitconfig
    state: link

- name: gitignore
  file:
    src: "{{ role_path }}/files/.gitignore"
    dest: ~/.gitignore
    state: link

- name: vimrc
  file:
    src: "{{ role_path }}/files/.vimrc"
    dest: ~/.vimrc
    state: link

- name: zshrc
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: ~/.zshrc
    state: link

- name: psqlrc
  file:
    src: "{{ role_path }}/files/.psqlrc"
    dest: ~/.psqlrc
    state: link

- name: tmux.conf
  file:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: ~/.tmux.conf
    state: link

- name: irssi
  file:
    src: "{{ role_path }}/files/.irssi"
    dest: ~/.irssi
    state: link

- name: karabiner dir
  file:
    dest: ~/.config/karabiner
    state: directory
    mode: '0755'

- name: karabiner.json
  file:
    src: "{{ role_path }}/files/karabiner.json"
    dest: ~/.config/karabiner/karabiner.json
    state: link
    force: yes

- name: Ensure bin directory
  file:
    path: ~/bin
    state: directory
    mode: '0755'
