#!/usr/bin/env bash ./bin/ansible-playbook-bootstrap.sh
#
---
- gather_facts: no
  hosts: personalmac
  become: false
  connection: local
  tasks:
  - name: Packages
    include_role:
      name: packages
      tasks_from: install.yaml
  - name: Symlinks
    include_role:
      name: symlinks
      tasks_from: install.yaml
  - name: Add-ons
    include_role:
      name: addons
      tasks_from: install.yaml
