---
- name: ensure vundle
  shell: test -f ~/.vim/bundle/Vundle.vim
  failed_when: test_vundle_file.rc not in [0, 1]
  register: test_vundle_file

- name: install vundle
  shell: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  register: vundle_plugin_install
  when: test_vundle_file.rc != 0
  failed_when: vundle_plugin_install.rc not in [0, 128]

- name: vim +PluginInstall
  shell: /usr/local/bin/vim +PluginInstall +qall
  args:
    creates: ~/.vimr/bundle/YouCompleteMe

- name: YCM libraries
  shell: ./install.sh
  args:
    chdir: ~/.vim/bundle/YouCompleteMe/
    creates: ~/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/cregex/regex_2/_regex.so

- name: oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" && ln -sf ~/.zshrc.pre-oh-my-zsh ~/.zshrc
  args:
    creates: ~/.oh-my-zsh/oh-my-zsh.sh
