PATH="$HOME/bin:/usr/local/bin:/usr/bin/perlbin/core:/opt/local/bin:$PATH"
typeset -U path # rid duplicates

MANPATH="/usr/local/man:/opt/local/man:$MANPATH"
typeset -U manpath # rid duplicates

export EDITOR="vim"
setopt noglobalrcs
