if [ -d "$HOME/.oh-my-zsh" ]
then
    ZSH=$HOME/.oh-my-zsh
    ZSH_THEME="robbyrussell"
    plugins=(git github git-flow)
    source $ZSH/oh-my-zsh.sh
fi

[ -d ~/.zscripts ] &&  find ~/.zscripts/ \( -type f -o -type l \) -name '*.zsh' | sort | \
    while read z; do source "$z"; done

unsetopt correct_all
if [ -e "${HOME}/.weeblyrc" ]; then source "${HOME}/.weeblyrc"; fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
