function precmd() {
    [ -x "$(which shell-prompt)" ] && PROMPT=`shell-prompt`
}

. ~/.zshcomplete

HISTFILE=$HOME/.history
HISTSIZE=100000
SAVEHIST=100000

setopt extended_history
setopt share_history
setopt hist_ignore_space

autoload copy-earlier-word
zle -N copy-earlier-word

autoload edit-command-line
zle -N edit-command-line

setopt nobeep
setopt auto_cd
setopt multios
setopt extended_glob
setopt nullglob
setopt list_ambiguous
setopt no_nomatch
setopt interactivecomments
setopt listpacked
setopt complete_in_word

bindkey -v
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^N" accept-and-infer-next-history
bindkey "^P" push-line
bindkey "^R" history-incremental-search-backward
bindkey "^Y" copy-earlier-word
bindkey "^T" transpose-chars
bindkey " " magic-space
bindkey "\e[3~" delete-char
bindkey -M vicmd v edit-command-line

alias ls='ls --color=auto --hide=_darcs'
alias grep='grep --color=auto'
alias ack='ack --color'
export ACK_COLOR_FILENAME=clear
export ACK_COLOR_MATCH=red
alias nao="TERM=rxvt telnet nethack.alt.org"
alias termcast="telnet termcast.org"
alias i='sudo port install'
alias s='sudo port search'
alias v='sudo port variants'
alias ci='sudo cpan -i'
alias ll='ls -lhA'
alias less='less -R'
alias p='prove -lr'
alias pp='prove -lr --state=hot,new,save -j10 -r'
alias pv='prove -lr --state=failed,save -v -r'
alias mmi='make && sudo make install'
alias pmmi='perl Makefile.PL && mmi'
alias sl='ls'
alias httpd="sudo httpd"
alias linode="ssh j.asonmay.net"
alias ar='sudo /etc/init.d/apache2 restart'
alias downgrade-to-cpan='git reset --hard $(git describe --abbrev=0)'
alias syntax-perl='ls lib/**/*.pm | while read pm; do perl -Ilib -c "$pm"; done'

function mud() {
    rlwrap telnet "$1" 6715
}

function pubkey() {
    ssh "$1" "cat - >> .ssh/authorized_keys" < .ssh/id_dsa.pub
}

# doy rules
function mem_usage {
    ps -eo size,ucmd | sort -rn | head -n$([ -z "$1" ] && echo 20 || echo $1)
}

function cpan_checkliset {
    echo "Did you make sure all the POD looks ok?"
    echo "run 'syntax-perl'"
    echo "Did you update Changes?"
    echo "Did you clear what was completed in TODO?"
    echo "Run your tests!"
}
